//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeastFreedom03.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kitchen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitchen()
        {
            this.Items = new HashSet<Item>();
            this.KitchenHOOps = new HashSet<KitchenHOOp>();
        }
        [Display(Name = "Kitchen ID")]
        public int KitchenID { get; set; }
        [Display (Name = "Kitchen Name")]
        public string KitchenName { get; set; }
        [Display (Name = "E-mail")]
        public string KitchenEmail { get; set; }
        [Display (Name = "Password")]
        public string KitchenPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitchenHOOp> KitchenHOOps { get; set; }
    }
}
